### ISSUE TITLE
Double scan for unlock 

### ISSUE THREAD

**Issue by fkreiner** [sschaeffner/fabXclient#1] opened 2020-03-16 19:30 UTC
* sometimes clients with a single tool require a second scan for unlocking
* scan works but tool is not unlocked

**Comment by sschmitt98** [comment] 2020-04-27 19:54
Cannot reproduce at home.
When setting the HTTPClient's timeout and connect timeout too low (i.e. <1000ms), the ESP does not receive any HTTP replies.
With connect timeout = 1000ms and timeout = 500ms the request is reliable here.

Maybe the 2.4GHz band is a bit crowded at the lab.

**Comment by sschmitt98** [comment] 2020-09-15 17:32
Seems to be fixed by connecting to a more lightly used WiFi network and disabling WiFi power saving.

**Closed as completed by sschmitt98** 2020-09-15 17:32 UTC
Labels: bug

**Comment by sschmitt98** [comment] 2020-10-14 09:23
Maybe happened due to a misconfiguration of DNS resolvers in the previously used network. The TTL of the backend domain is currently 60 seconds which would explain it working the second time but then failing again after some time.
